const std = @import("std");

pub const Declaration = struct {
    name: []const u8,
    c: []const u8,
};

pub const declarations = [_]Declaration{
    .{ .name = "minna_san_abi_version", .c = "minna_san_abi_version_t minna_san_abi_version(void);" },
    .{ .name = "minna_san_abi_supports_version", .c = "uint8_t minna_san_abi_supports_version(minna_san_abi_version_t requested_version);" },
    .{ .name = "minna_san_result_is_known", .c = "uint8_t minna_san_result_is_known(int result_code);" },
    .{ .name = "minna_san_result_category", .c = "minna_san_error_category minna_san_result_category(int result_code);" },
    .{ .name = "minna_san_result_retryability", .c = "minna_san_retryability minna_san_result_retryability(int result_code);" },
    .{ .name = "minna_san_result_operator_category", .c = "minna_san_operator_category minna_san_result_operator_category(int result_code);" },
    .{ .name = "minna_san_result_message", .c = "const char *minna_san_result_message(int result_code);" },
    .{ .name = "minna_san_endpoint_parse", .c = "minna_san_result minna_san_endpoint_parse(minna_san_const_buffer text, uint16_t port, minna_san_endpoint *out_endpoint);" },
    .{ .name = "minna_san_endpoint_format", .c = "minna_san_result minna_san_endpoint_format(const minna_san_endpoint *endpoint, minna_san_buffer output, size_t *out_len);" },
    .{ .name = "minna_san_endpoint_equal", .c = "uint8_t minna_san_endpoint_equal(const minna_san_endpoint *left, const minna_san_endpoint *right);" },
    .{ .name = "minna_san_platform_config_init", .c = "minna_san_result minna_san_platform_config_init(minna_san_platform_config *out_config);" },
    .{ .name = "minna_san_platform_config_validate", .c = "minna_san_result minna_san_platform_config_validate(const minna_san_platform_config *config);" },
    .{ .name = "minna_san_sdk_validate_config", .c = "minna_san_result minna_san_sdk_validate_config(const minna_san_sdk_config *config);" },
    .{ .name = "minna_san_sdk_create", .c = "minna_san_result minna_san_sdk_create(const minna_san_sdk_config *config, minna_san_sdk **out_sdk);" },
    .{ .name = "minna_san_sdk_start", .c = "minna_san_result minna_san_sdk_start(minna_san_sdk *sdk);" },
    .{ .name = "minna_san_sdk_poll", .c = "minna_san_result minna_san_sdk_poll(minna_san_sdk *sdk, minna_san_event *out_event);" },
    .{ .name = "minna_san_sdk_stop", .c = "minna_san_result minna_san_sdk_stop(minna_san_sdk *sdk);" },
    .{ .name = "minna_san_sdk_destroy", .c = "void minna_san_sdk_destroy(minna_san_sdk *sdk);" },
    .{ .name = "minna_san_native_runtime_create", .c = "minna_san_result minna_san_native_runtime_create(const minna_san_sdk_config *config, minna_san_native_runtime **out_runtime);" },
    .{ .name = "minna_san_native_runtime_destroy", .c = "void minna_san_native_runtime_destroy(minna_san_native_runtime *native_runtime);" },
    .{ .name = "minna_san_native_udp_config_validate", .c = "minna_san_result minna_san_native_udp_config_validate(const minna_san_native_udp_config *config);" },
    .{ .name = "minna_san_native_udp_dial", .c = "minna_san_result minna_san_native_udp_dial(minna_san_native_runtime *native_runtime, const minna_san_native_udp_config *config, minna_san_native_session **out_session, minna_san_native_channel **out_channel);" },
    .{ .name = "minna_san_native_udp_poll", .c = "minna_san_result minna_san_native_udp_poll(minna_san_native_runtime *native_runtime, minna_san_native_session *session, minna_san_native_channel **out_channel);" },
    .{ .name = "minna_san_native_udp_session_address", .c = "minna_san_result minna_san_native_udp_session_address(minna_san_native_runtime *native_runtime, minna_san_native_session *session, minna_san_address *out_address);" },
    .{ .name = "minna_san_native_channel_send", .c = "minna_san_result minna_san_native_channel_send(minna_san_native_runtime *native_runtime, minna_san_native_channel *channel, minna_san_const_buffer payload);" },
    .{ .name = "minna_san_native_udp_flush", .c = "minna_san_result minna_san_native_udp_flush(minna_san_native_runtime *native_runtime, minna_san_native_session *session, size_t *out_sent);" },
    .{ .name = "minna_san_native_udp_receive", .c = "minna_san_result minna_san_native_udp_receive(minna_san_native_runtime *native_runtime, minna_san_native_session *session, minna_san_native_channel **out_channel, minna_san_buffer *out_payload);" },
    .{ .name = "minna_san_native_buffer_release", .c = "minna_san_result minna_san_native_buffer_release(minna_san_native_runtime *native_runtime, minna_san_buffer buffer);" },
    .{ .name = "minna_san_native_udp_session_close", .c = "minna_san_result minna_san_native_udp_session_close(minna_san_native_runtime *native_runtime, minna_san_native_session *session);" },
    .{ .name = "minna_san_channel_open", .c = "minna_san_result minna_san_channel_open(minna_san_sdk *sdk, minna_san_connection *connection, uint32_t mode, minna_san_channel **out_channel);" },
    .{ .name = "minna_san_channel_close", .c = "minna_san_result minna_san_channel_close(minna_san_sdk *sdk, minna_san_channel *channel);" },
    .{ .name = "minna_san_channel_mode", .c = "minna_san_result minna_san_channel_mode(minna_san_sdk *sdk, minna_san_channel *channel, uint32_t *out_mode);" },
    .{ .name = "minna_san_channel_send", .c = "minna_san_result minna_san_channel_send(minna_san_sdk *sdk, minna_san_channel *channel, minna_san_buffer buffer, uint64_t *out_sequence);" },
    .{ .name = "minna_san_channel_receive", .c = "minna_san_result minna_san_channel_receive(minna_san_sdk *sdk, minna_san_channel *channel, minna_san_buffer *out_buffer, uint64_t *out_sequence);" },
    .{ .name = "minna_san_channel_acknowledge", .c = "minna_san_result minna_san_channel_acknowledge(minna_san_sdk *sdk, minna_san_channel *channel, uint64_t sequence);" },
    .{ .name = "minna_san_channel_last_acknowledged", .c = "minna_san_result minna_san_channel_last_acknowledged(minna_san_sdk *sdk, minna_san_channel *channel, uint64_t *out_sequence);" },
    .{ .name = "minna_san_sdk_buffer_release", .c = "minna_san_result minna_san_sdk_buffer_release(minna_san_sdk *sdk, minna_san_buffer buffer);" },
    .{ .name = "minna_san_security_config_init", .c = "minna_san_result minna_san_security_config_init(minna_san_security_config *out_config);" },
    .{ .name = "minna_san_security_config_set_psk", .c = "minna_san_result minna_san_security_config_set_psk(minna_san_security_config *config, minna_san_buffer psk);" },
    .{ .name = "minna_san_security_config_set_public_key", .c = "minna_san_result minna_san_security_config_set_public_key(minna_san_security_config *config, minna_san_buffer public_key);" },
    .{ .name = "minna_san_security_config_set_aead_key", .c = "minna_san_result minna_san_security_config_set_aead_key(minna_san_security_config *config, minna_san_buffer aead_key);" },
    .{ .name = "minna_san_security_config_set_replay_window", .c = "minna_san_result minna_san_security_config_set_replay_window(minna_san_security_config *config, uint32_t replay_window);" },
    .{ .name = "minna_san_security_config_set_key_rotation", .c = "minna_san_result minna_san_security_config_set_key_rotation(minna_san_security_config *config, minna_san_duration_ns interval_ns, minna_san_duration_ns overlap_ns);" },
    .{ .name = "minna_san_security_config_validate", .c = "minna_san_result minna_san_security_config_validate(const minna_san_security_config *config);" },
    .{ .name = "minna_san_authoritative_session_config_init", .c = "minna_san_result minna_san_authoritative_session_config_init(minna_san_authoritative_session_config *out_config);" },
    .{ .name = "minna_san_authoritative_session_config_validate", .c = "minna_san_result minna_san_authoritative_session_config_validate(const minna_san_authoritative_session_config *config);" },
    .{ .name = "minna_san_authoritative_session_create", .c = "minna_san_result minna_san_authoritative_session_create(minna_san_sdk *sdk, const minna_san_authoritative_session_config *config, minna_san_authoritative_session **out_session);" },
    .{ .name = "minna_san_authoritative_session_state", .c = "minna_san_result minna_san_authoritative_session_state(minna_san_sdk *sdk, minna_san_authoritative_session *session, uint32_t *out_state);" },
    .{ .name = "minna_san_authoritative_session_transition", .c = "minna_san_result minna_san_authoritative_session_transition(minna_san_sdk *sdk, minna_san_authoritative_session *session, uint32_t transition);" },
    .{ .name = "minna_san_authoritative_session_destroy", .c = "minna_san_result minna_san_authoritative_session_destroy(minna_san_sdk *sdk, minna_san_authoritative_session *session);" },
    .{ .name = "minna_san_authoritative_session_client_join", .c = "minna_san_result minna_san_authoritative_session_client_join(minna_san_sdk *sdk, minna_san_authoritative_session *session, minna_san_connection *connection);" },
    .{ .name = "minna_san_authoritative_session_client_leave", .c = "minna_san_result minna_san_authoritative_session_client_leave(minna_san_sdk *sdk, minna_san_authoritative_session *session, minna_san_connection *connection);" },
    .{ .name = "minna_san_authoritative_session_client_count", .c = "minna_san_result minna_san_authoritative_session_client_count(minna_san_sdk *sdk, minna_san_authoritative_session *session, size_t *out_count);" },
    .{ .name = "minna_san_topology_config_init", .c = "minna_san_result minna_san_topology_config_init(minna_san_topology_config *out_config);" },
    .{ .name = "minna_san_topology_config_set_p2p", .c = "minna_san_result minna_san_topology_config_set_p2p(minna_san_topology_config *config, minna_san_p2p_config p2p);" },
    .{ .name = "minna_san_topology_config_set_stun_turn", .c = "minna_san_result minna_san_topology_config_set_stun_turn(minna_san_topology_config *config, minna_san_stun_turn_config stun_turn);" },
    .{ .name = "minna_san_topology_config_set_migration", .c = "minna_san_result minna_san_topology_config_set_migration(minna_san_topology_config *config, minna_san_migration_config migration);" },
    .{ .name = "minna_san_topology_config_validate", .c = "minna_san_result minna_san_topology_config_validate(const minna_san_topology_config *config);" },
    .{ .name = "minna_san_topology_capabilities_config_init", .c = "minna_san_result minna_san_topology_capabilities_config_init(minna_san_topology_capabilities_config *out_config);" },
    .{ .name = "minna_san_topology_capabilities_config_set_authoritative_recovery", .c = "minna_san_result minna_san_topology_capabilities_config_set_authoritative_recovery(minna_san_topology_capabilities_config *config, minna_san_authoritative_recovery_config authoritative_recovery);" },
    .{ .name = "minna_san_topology_capabilities_config_set_sharded_p2p", .c = "minna_san_result minna_san_topology_capabilities_config_set_sharded_p2p(minna_san_topology_capabilities_config *config, minna_san_sharded_p2p_config sharded_p2p);" },
    .{ .name = "minna_san_topology_capabilities_config_set_stun", .c = "minna_san_result minna_san_topology_capabilities_config_set_stun(minna_san_topology_capabilities_config *config, minna_san_stun_config stun);" },
    .{ .name = "minna_san_topology_capabilities_config_set_turn", .c = "minna_san_result minna_san_topology_capabilities_config_set_turn(minna_san_topology_capabilities_config *config, minna_san_turn_config turn);" },
    .{ .name = "minna_san_topology_capabilities_config_set_route", .c = "minna_san_result minna_san_topology_capabilities_config_set_route(minna_san_topology_capabilities_config *config, minna_san_route_config route);" },
    .{ .name = "minna_san_topology_capabilities_config_set_migration_transfer", .c = "minna_san_result minna_san_topology_capabilities_config_set_migration_transfer(minna_san_topology_capabilities_config *config, minna_san_migration_transfer_config migration_transfer);" },
    .{ .name = "minna_san_topology_capabilities_config_validate", .c = "minna_san_result minna_san_topology_capabilities_config_validate(const minna_san_topology_capabilities_config *config);" },
    .{ .name = "minna_san_state_transfer_config_init", .c = "minna_san_result minna_san_state_transfer_config_init(minna_san_state_transfer_config *out_config);" },
    .{ .name = "minna_san_state_transfer_config_set_callbacks", .c = "minna_san_result minna_san_state_transfer_config_set_callbacks(minna_san_state_transfer_config *config, void *context, minna_san_state_transform_fn serialize, minna_san_state_transform_fn deserialize);" },
    .{ .name = "minna_san_state_transfer_config_set_snapshot_limits", .c = "minna_san_result minna_san_state_transfer_config_set_snapshot_limits(minna_san_state_transfer_config *config, size_t max_snapshot_bytes, size_t max_delta_bytes);" },
    .{ .name = "minna_san_state_transfer_config_set_recovery", .c = "minna_san_result minna_san_state_transfer_config_set_recovery(minna_san_state_transfer_config *config, minna_san_duration_ns recovery_timeout_ns, uint32_t template_kind);" },
    .{ .name = "minna_san_state_transfer_config_validate", .c = "minna_san_result minna_san_state_transfer_config_validate(const minna_san_state_transfer_config *config);" },
    .{ .name = "minna_san_state_transfer_serialize", .c = "minna_san_result minna_san_state_transfer_serialize(const minna_san_state_transfer_config *config, minna_san_buffer input, minna_san_buffer *out_snapshot);" },
    .{ .name = "minna_san_state_transfer_deserialize", .c = "minna_san_result minna_san_state_transfer_deserialize(const minna_san_state_transfer_config *config, minna_san_buffer input, minna_san_buffer *out_state);" },
    .{ .name = "minna_san_sdk_metrics_snapshot", .c = "minna_san_result minna_san_sdk_metrics_snapshot(minna_san_sdk *sdk, minna_san_metrics_snapshot *out_snapshot);" },
    .{ .name = "minna_san_sdk_runtime_metrics_snapshot", .c = "minna_san_result minna_san_sdk_runtime_metrics_snapshot(minna_san_sdk *sdk, minna_san_runtime_metrics_snapshot *out_snapshot);" },
    .{ .name = "minna_san_sdk_log_callback_register", .c = "minna_san_result minna_san_sdk_log_callback_register(minna_san_sdk *sdk, void *context, minna_san_log_record_fn callback, minna_san_log_subscription *out_subscription);" },
    .{ .name = "minna_san_sdk_log_callback_unregister", .c = "minna_san_result minna_san_sdk_log_callback_unregister(minna_san_sdk *sdk, minna_san_log_subscription subscription);" },
    .{ .name = "minna_san_sdk_log", .c = "minna_san_result minna_san_sdk_log(minna_san_sdk *sdk, uint32_t level, uint32_t category, uint32_t redaction, minna_san_buffer message);" },
    .{ .name = "minna_san_diagnostics_config_init", .c = "minna_san_result minna_san_diagnostics_config_init(minna_san_diagnostics_config *out_config);" },
    .{ .name = "minna_san_diagnostics_config_set_logging", .c = "minna_san_result minna_san_diagnostics_config_set_logging(minna_san_diagnostics_config *config, void *context, minna_san_log_fn log, uint32_t level);" },
    .{ .name = "minna_san_diagnostics_config_set_capture_replay", .c = "minna_san_result minna_san_diagnostics_config_set_capture_replay(minna_san_diagnostics_config *config, uint8_t capture_enabled, uint8_t replay_enabled, uint8_t redact_payloads, size_t max_capture_bytes);" },
    .{ .name = "minna_san_diagnostics_config_validate", .c = "minna_san_result minna_san_diagnostics_config_validate(const minna_san_diagnostics_config *config);" },
    .{ .name = "minna_san_diagnostics_log", .c = "minna_san_result minna_san_diagnostics_log(const minna_san_diagnostics_config *config, const char *message);" },
    .{ .name = "minna_san_connection_open", .c = "minna_san_result minna_san_connection_open(minna_san_sdk *sdk, uint32_t route_state, minna_san_connection **out_connection, minna_san_peer **out_peer);" },
    .{ .name = "minna_san_connection_close", .c = "minna_san_result minna_san_connection_close(minna_san_sdk *sdk, minna_san_connection *connection);" },
    .{ .name = "minna_san_connection_peer", .c = "minna_san_result minna_san_connection_peer(minna_san_sdk *sdk, minna_san_connection *connection, minna_san_peer **out_peer);" },
    .{ .name = "minna_san_connection_route_state", .c = "minna_san_result minna_san_connection_route_state(minna_san_sdk *sdk, minna_san_connection *connection, uint32_t *out_route_state);" },
    .{ .name = "minna_san_connection_set_route_state", .c = "minna_san_result minna_san_connection_set_route_state(minna_san_sdk *sdk, minna_san_connection *connection, uint32_t route_state);" },
    .{ .name = "minna_san_p2p_session_create", .c = "minna_san_result minna_san_p2p_session_create(minna_san_sdk *sdk, minna_san_candidate candidate, minna_san_p2p_session **out_session);" },
    .{ .name = "minna_san_p2p_session_destroy", .c = "minna_san_result minna_san_p2p_session_destroy(minna_san_sdk *sdk, minna_san_p2p_session *session);" },
    .{ .name = "minna_san_p2p_session_set_candidate", .c = "minna_san_result minna_san_p2p_session_set_candidate(minna_san_sdk *sdk, minna_san_p2p_session *session, minna_san_candidate candidate);" },
    .{ .name = "minna_san_p2p_session_candidate", .c = "minna_san_result minna_san_p2p_session_candidate(minna_san_sdk *sdk, minna_san_p2p_session *session, minna_san_candidate *out_candidate);" },
    .{ .name = "minna_san_p2p_session_copy_signaling", .c = "minna_san_result minna_san_p2p_session_copy_signaling(minna_san_sdk *sdk, minna_san_p2p_session *session, minna_san_const_buffer signaling, minna_san_buffer *out_copy);" },
    .{ .name = "minna_san_p2p_session_route_state", .c = "minna_san_result minna_san_p2p_session_route_state(minna_san_sdk *sdk, minna_san_p2p_session *session, uint32_t *out_route_state);" },
    .{ .name = "minna_san_p2p_session_fallback_relay", .c = "minna_san_result minna_san_p2p_session_fallback_relay(minna_san_sdk *sdk, minna_san_p2p_session *session);" },
    .{ .name = "minna_san_event_kind", .c = "uint32_t minna_san_event_kind(const minna_san_event *event);" },
    .{ .name = "minna_san_event_mode", .c = "uint32_t minna_san_event_mode(const minna_san_event *event);" },
    .{ .name = "minna_san_event_sequence", .c = "uint64_t minna_san_event_sequence(const minna_san_event *event);" },
    .{ .name = "minna_san_event_payload", .c = "minna_san_buffer minna_san_event_payload(const minna_san_event *event);" },
    .{ .name = "minna_san_transport_config_init", .c = "minna_san_result minna_san_transport_config_init(minna_san_transport_config *out_config);" },
    .{ .name = "minna_san_transport_config_set_kind", .c = "minna_san_result minna_san_transport_config_set_kind(minna_san_transport_config *config, uint32_t kind);" },
    .{ .name = "minna_san_transport_config_set_local_address", .c = "minna_san_result minna_san_transport_config_set_local_address(minna_san_transport_config *config, minna_san_address address);" },
    .{ .name = "minna_san_transport_config_set_remote_address", .c = "minna_san_result minna_san_transport_config_set_remote_address(minna_san_transport_config *config, minna_san_address address);" },
    .{ .name = "minna_san_transport_config_set_socket_options", .c = "minna_san_result minna_san_transport_config_set_socket_options(minna_san_transport_config *config, minna_san_socket_options options);" },
    .{ .name = "minna_san_transport_config_set_control", .c = "minna_san_result minna_san_transport_config_set_control(minna_san_transport_config *config, minna_san_transport_control control);" },
    .{ .name = "minna_san_transport_config_validate", .c = "minna_san_result minna_san_transport_config_validate(const minna_san_transport_config *config);" },
};

test "C API declaration inventory has unique named declarations" {
    for (declarations, 0..) |declaration, index| {
        try std.testing.expect(declaration.name.len != 0);
        try std.testing.expect(std.mem.indexOf(u8, declaration.c, declaration.name) != null);
        for (declarations[0..index]) |previous| try std.testing.expect(!std.mem.eql(u8, declaration.name, previous.name));
    }
}
