const core = @import("minna-san-core");
const protocol = @import("minna-san-protocol");
const migration_coordinator = @import("migration_coordinator.zig");
const host_election = @import("host_election.zig");
const migration_state_transfer = @import("migration_state_transfer.zig");
const serialization_contract = @import("serialization_contract.zig");
const state_encoder = @import("state_encoder.zig");
const state_decoder = @import("state_decoder.zig");
const snapshot_publisher = @import("snapshot_publisher.zig");
const snapshot_client = @import("snapshot_client.zig");
const snapshot_baseline = @import("snapshot_baseline.zig");
const full_state_recovery = @import("full_state_recovery.zig");
const replication_template = @import("replication_template.zig");

pub const max_migration_records = migration_coordinator.max_migration_records;
pub const MigrationTerm = migration_coordinator.MigrationTerm;
pub const MigrationHostId = migration_coordinator.MigrationHostId;
pub const MigrationRoute = migration_coordinator.MigrationRoute;
pub const MigrationHostHealth = migration_coordinator.MigrationHostHealth;
pub const MigrationRecordState = migration_coordinator.MigrationRecordState;
pub const MigrationPlan = migration_coordinator.MigrationPlan;
pub const MigrationRecord = migration_coordinator.MigrationRecord;
pub const MigrationCoordinatorError = migration_coordinator.MigrationCoordinatorError;
pub const MigrationCoordinatorConfig = migration_coordinator.MigrationCoordinatorConfig;
pub const MigrationCoordinator = migration_coordinator.MigrationCoordinator;
pub const HostElectionOrder = host_election.HostElectionOrder;
pub const HostElectionMember = host_election.HostElectionMember;
pub const HostElection = host_election.HostElection;
pub const HostElectionError = host_election.HostElectionError;
pub const HostElectionConfig = host_election.HostElectionConfig;
pub const HostElector = host_election.HostElector;
pub const migration_transfer_integrity_tag_bytes = migration_state_transfer.migration_transfer_integrity_tag_bytes;
pub const MigrationStateMetadata = migration_state_transfer.MigrationStateMetadata;
pub const AcknowledgedMigrationSnapshot = migration_state_transfer.AcknowledgedMigrationSnapshot;
pub const MigrationStateTransferFrame = migration_state_transfer.MigrationStateTransferFrame;
pub const MigrationStateTransferError = migration_state_transfer.MigrationStateTransferError;
pub const MigrationStateTransferConfig = migration_state_transfer.MigrationStateTransferConfig;
pub const MigrationStateTransfer = migration_state_transfer.MigrationStateTransfer;
pub const StateSchemaVersion = serialization_contract.StateSchemaVersion;
pub const StateSerializationFailure = serialization_contract.StateSerializationFailure;
pub const StateSerializationError = serialization_contract.StateSerializationError;
pub const StateSerializationAllocateFn = serialization_contract.StateSerializationAllocateFn;
pub const StateSerializationReleaseFn = serialization_contract.StateSerializationReleaseFn;
pub const StateSerializationAllocation = serialization_contract.StateSerializationAllocation;
pub const StateSerializationFrame = serialization_contract.StateSerializationFrame;
pub const StateSchemaVersionFn = serialization_contract.StateSchemaVersionFn;
pub const StateSerializeFn = serialization_contract.StateSerializeFn;
pub const StateDeserializeFn = serialization_contract.StateDeserializeFn;
pub const StateSerializationDeterminismFn = serialization_contract.StateSerializationDeterminismFn;
pub const StateSerializationFailureFn = serialization_contract.StateSerializationFailureFn;
pub const StateSerializationCallbacks = serialization_contract.StateSerializationCallbacks;
pub const StateSerializationConfig = serialization_contract.StateSerializationConfig;
pub const StateSerializationContract = serialization_contract.StateSerializationContract;
pub const StateEncodeFailure = state_encoder.StateEncodeFailure;
pub const StateEncodeError = state_encoder.StateEncodeError;
pub const StateEncodeChunk = state_encoder.StateEncodeChunk;
pub const StateEncodeStreamFn = state_encoder.StateEncodeStreamFn;
pub const StateEncodeStream = state_encoder.StateEncodeStream;
pub const StateEncodeFailureFn = state_encoder.StateEncodeFailureFn;
pub const StateEncoderConfig = state_encoder.StateEncoderConfig;
pub const StateEncoder = state_encoder.StateEncoder;
pub const StateDecodeFailure = state_decoder.StateDecodeFailure;
pub const StateDecodeError = state_decoder.StateDecodeError;
pub const StateSchemaCompatibilityFn = state_decoder.StateSchemaCompatibilityFn;
pub const StateDecodeFailureFn = state_decoder.StateDecodeFailureFn;
pub const StateDecoderConfig = state_decoder.StateDecoderConfig;
pub const StateDecoder = state_decoder.StateDecoder;
pub const StateSnapshotSequence = snapshot_publisher.StateSnapshotSequence;
pub const StateSnapshotSubscriberId = snapshot_publisher.StateSnapshotSubscriberId;
pub const StateSnapshotError = snapshot_publisher.StateSnapshotError;
pub const StateSnapshot = snapshot_publisher.StateSnapshot;
pub const StateSnapshotSubscriber = snapshot_publisher.StateSnapshotSubscriber;
pub const StateSnapshotPublisherConfig = snapshot_publisher.StateSnapshotPublisherConfig;
pub const StateSnapshotPublisher = snapshot_publisher.StateSnapshotPublisher;
pub const StateSnapshotDelivery = snapshot_client.StateSnapshotDelivery;
pub const StateSnapshotApplied = snapshot_client.StateSnapshotApplied;
pub const StateSnapshotApplyFn = snapshot_client.StateSnapshotApplyFn;
pub const StateSnapshotClientError = snapshot_client.StateSnapshotClientError;
pub const StateSnapshotClientConfig = snapshot_client.StateSnapshotClientConfig;
pub const StateSnapshotClient = snapshot_client.StateSnapshotClient;
pub const StateSnapshotBaselineError = snapshot_baseline.StateSnapshotBaselineError;
pub const StateSnapshotBaseline = snapshot_baseline.StateSnapshotBaseline;
pub const StateSnapshotBaselineConfig = snapshot_baseline.StateSnapshotBaselineConfig;
pub const StateSnapshotBaselines = snapshot_baseline.StateSnapshotBaselines;
pub const StateRecoveryRequestId = full_state_recovery.StateRecoveryRequestId;
pub const StateRecoveryReason = full_state_recovery.StateRecoveryReason;
pub const StateDeltaBaseline = full_state_recovery.StateDeltaBaseline;
pub const StateFullStateRecoveryRequest = full_state_recovery.StateFullStateRecoveryRequest;
pub const StateFullStateRecoveryError = full_state_recovery.StateFullStateRecoveryError;
pub const StateFullStateRecoveryConfig = full_state_recovery.StateFullStateRecoveryConfig;
pub const StateFullStateRecovery = full_state_recovery.StateFullStateRecovery;
pub const StateReplicationRecipient = replication_template.StateReplicationRecipient;
pub const StateReplicationInterestFn = replication_template.StateReplicationInterestFn;
pub const StateReplicationTransportFn = replication_template.StateReplicationTransportFn;
pub const StateReplicationInterest = replication_template.StateReplicationInterest;
pub const StateReplicationTransport = replication_template.StateReplicationTransport;
pub const StateReplicationError = replication_template.StateReplicationError;
pub const StateReplicationOutcome = replication_template.StateReplicationOutcome;
pub const StateReplicationTemplateConfig = replication_template.StateReplicationTemplateConfig;
pub const StateReplicationTemplate = replication_template.StateReplicationTemplate;

pub const package_name = "state";

comptime {
    _ = core.package_name;
    _ = protocol.package_name;
}

test "state package boundary" {
    try @import("std").testing.expectEqualStrings("state", package_name);
}

test {
    _ = @import("migration_coordinator.zig");
    _ = @import("host_election.zig");
    _ = @import("migration_state_transfer.zig");
    _ = @import("serialization_contract.zig");
    _ = @import("state_encoder.zig");
    _ = @import("state_decoder.zig");
    _ = @import("snapshot_publisher.zig");
    _ = @import("snapshot_client.zig");
    _ = @import("snapshot_baseline.zig");
    _ = @import("full_state_recovery.zig");
    _ = @import("replication_template.zig");
}
