// Command supportdoc renders the public support contract from its evidence ledger.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"regexp"
	"slices"
	"strings"
	"time"
)

const ledgerSchemaVersion = 1

var commitPattern = regexp.MustCompile(`^[0-9a-f]{40}$`)

type ledger struct {
	SchemaVersion int      `json:"schemaVersion"`
	Policy        string   `json:"policy"`
	Targets       []target `json:"targets"`
	Claims        []claim  `json:"claims"`
}

type target struct {
	ID               string `json:"id"`
	Label            string `json:"label"`
	Classification   string `json:"classification"`
	RequiredEvidence string `json:"requiredEvidence"`
}

type claim struct {
	ID        string `json:"id"`
	Target    string `json:"target"`
	Summary   string `json:"summary"`
	Commit    string `json:"commit"`
	OS        string `json:"os"`
	GPUDriver string `json:"gpuDriver"`
	Browser   string `json:"browser"`
	TestType  string `json:"testType"`
	Date      string `json:"date"`
}

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, "supportdoc:", err)
		os.Exit(1)
	}
}

func run(arguments []string) error {
	flags := flag.NewFlagSet("supportdoc", flag.ContinueOnError)
	input := flags.String("in", "docs/support-evidence.json", "evidence ledger JSON path")
	output := flags.String("out", "docs/SUPPORT.md", "generated Markdown path")
	check := flags.Bool("check", false, "fail unless output matches generated Markdown")
	if err := flags.Parse(arguments); err != nil {
		return err
	}
	if flags.NArg() != 0 {
		return errors.New("accepts flags only")
	}
	data, err := os.ReadFile(*input)
	if err != nil {
		return fmt.Errorf("read evidence ledger: %w", err)
	}
	ledger, err := decodeLedger(data)
	if err != nil {
		return err
	}
	document := render(ledger)
	if *check {
		existing, err := os.ReadFile(*output)
		if err != nil {
			return fmt.Errorf("read generated support document: %w", err)
		}
		if !bytes.Equal(existing, document) {
			return fmt.Errorf("%s is stale; run go run ./cmd/supportdoc -in %s -out %s", *output, *input, *output)
		}
		return nil
	}
	if err := os.WriteFile(*output, document, 0o644); err != nil {
		return fmt.Errorf("write generated support document: %w", err)
	}
	return nil
}

func decodeLedger(data []byte) (ledger, error) {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	var value ledger
	if err := decoder.Decode(&value); err != nil {
		return ledger{}, fmt.Errorf("decode evidence ledger: %w", err)
	}
	var trailing any
	if err := decoder.Decode(&trailing); !errors.Is(err, io.EOF) {
		if err == nil {
			return ledger{}, errors.New("decode evidence ledger: expected one JSON value")
		}
		return ledger{}, fmt.Errorf("decode evidence ledger trailing value: %w", err)
	}
	if err := validate(value); err != nil {
		return ledger{}, err
	}
	return value, nil
}

func validate(value ledger) error {
	if value.SchemaVersion != ledgerSchemaVersion {
		return fmt.Errorf("evidence ledger schemaVersion must be %d", ledgerSchemaVersion)
	}
	if strings.TrimSpace(value.Policy) == "" {
		return errors.New("evidence ledger policy must not be empty")
	}
	if len(value.Targets) == 0 {
		return errors.New("evidence ledger must define at least one target")
	}
	targetIDs := make([]string, 0, len(value.Targets))
	for _, target := range value.Targets {
		if strings.TrimSpace(target.ID) == "" || strings.TrimSpace(target.Label) == "" || strings.TrimSpace(target.Classification) == "" || strings.TrimSpace(target.RequiredEvidence) == "" {
			return fmt.Errorf("target %+v has an empty required field", target)
		}
		if slices.Contains(targetIDs, target.ID) {
			return fmt.Errorf("duplicate target %q", target.ID)
		}
		targetIDs = append(targetIDs, target.ID)
	}
	claimIDs := make([]string, 0, len(value.Claims))
	for _, claim := range value.Claims {
		if strings.TrimSpace(claim.ID) == "" || strings.TrimSpace(claim.Summary) == "" || strings.TrimSpace(claim.OS) == "" || strings.TrimSpace(claim.GPUDriver) == "" || strings.TrimSpace(claim.Browser) == "" || strings.TrimSpace(claim.TestType) == "" {
			return fmt.Errorf("claim %+v has an empty required field", claim)
		}
		if !slices.Contains(targetIDs, claim.Target) {
			return fmt.Errorf("claim %q names unknown target %q", claim.ID, claim.Target)
		}
		if !commitPattern.MatchString(claim.Commit) {
			return fmt.Errorf("claim %q commit must be a full lowercase Git SHA", claim.ID)
		}
		if _, err := time.Parse("2006-01-02", claim.Date); err != nil {
			return fmt.Errorf("claim %q date must be YYYY-MM-DD: %w", claim.ID, err)
		}
		if slices.Contains(claimIDs, claim.ID) {
			return fmt.Errorf("duplicate claim %q", claim.ID)
		}
		claimIDs = append(claimIDs, claim.ID)
	}
	return nil
}

func render(value ledger) []byte {
	var output strings.Builder
	output.WriteString("<!-- Code generated by go run ./cmd/supportdoc -in docs/support-evidence.json -out docs/SUPPORT.md; DO NOT EDIT. -->\n\n")
	output.WriteString("# Build and runtime evidence matrix\n\n")
	output.WriteString(value.Policy)
	output.WriteString("\n\n")
	output.WriteString("## Public target classification\n\n")
	output.WriteString("| Target | Current classification | Evidence required before promotion |\n")
	output.WriteString("| --- | --- | --- |\n")
	for _, target := range value.Targets {
		fmt.Fprintf(&output, "| %s | %s | %s |\n", markdown(target.Label), markdown(target.Classification), markdown(target.RequiredEvidence))
	}
	output.WriteString("\n## Recorded evidence\n\n")
	if len(value.Claims) == 0 {
		output.WriteString("No evidence record currently meets this ledger's complete metadata contract. Historical prose and a configured workflow are not certification evidence.\n")
	} else {
		output.WriteString("| Claim | Target | Commit | OS | GPU / driver | Browser | Test type | Date |\n")
		output.WriteString("| --- | --- | --- | --- | --- | --- | --- | --- |\n")
		for _, claim := range value.Claims {
			fmt.Fprintf(&output, "| %s | %s | `%s` | %s | %s | %s | %s | %s |\n", markdown(claim.Summary), markdown(claim.Target), claim.Commit, markdown(claim.OS), markdown(claim.GPUDriver), markdown(claim.Browser), markdown(claim.TestType), claim.Date)
		}
	}
	output.WriteString("\n## Recording a claim\n\n")
	output.WriteString("Add an entry to `docs/support-evidence.json` only after the stated test runs. Every entry requires a full 40-character commit SHA, operating system, GPU and driver observation (or an explicit `not observed` value for a non-GPU test), browser and version (or `not applicable`), test type, and UTC date. Regenerate this file with `make support-doc`; CI rejects a stale document with `make support-check`. A build, unit test, or fallback-adapter result cannot promote a target to runtime-certified support.\n\n")
	output.WriteString("## Browser product boundary\n\n")
	output.WriteString("For v0.1, browser delivery is **WebGPU-only experimental**. It requires a secure context and does not claim broad browser availability. There is no WebGL fallback. A future broadly deployable web-games product requires a separately designed, tested, and supported fallback backend rather than a compatibility patch.\n\n")
	output.WriteString("## Required runtime matrix\n\n")
	output.WriteString("Before changing a target classification, run and record Linux X11, Windows, macOS, Chromium, Firefox, and Safari as applicable. For each claimed target, cover resize, DPI changes, minimize/restore, user-initiated close, texture upload, device loss/recovery, and clean shutdown. Browser entries must also record HTTPS or localhost secure-context conditions. `72 doctor` remains diagnostic-only and always reports certification as `unverified`.\n")
	return []byte(output.String())
}

func markdown(value string) string {
	return strings.ReplaceAll(strings.ReplaceAll(value, "|", "\\|"), "\n", "<br>")
}
