const core = @import("minna-san-core");
const envelope = @import("wire_envelope.zig");
const packet_envelope = @import("packet_envelope.zig");
const capability_negotiation = @import("capability_negotiation.zig");
const extension_handling = @import("extension_handling.zig");
const reliable_ordered = @import("reliable_ordered.zig");
const unreliable_sequenced = @import("unreliable_sequenced.zig");
const ack_ranges = @import("ack_ranges.zig");
const retransmission = @import("retransmission.zig");
const congestion_controller = @import("congestion_controller.zig");
const baseline_congestion = @import("baseline_congestion.zig");
const packet_pacing = @import("packet_pacing.zig");
const bandwidth_caps = @import("bandwidth_caps.zig");
const backpressure = @import("backpressure.zig");

pub const WireVersion = envelope.WireVersion;
pub const ExtensionRange = envelope.ExtensionRange;
pub const WireEnvelope = envelope.WireEnvelope;
pub const CompatibilityError = envelope.CompatibilityError;
pub const v1_version = envelope.v1_version;
pub const extension_range = envelope.extension_range;
pub const validate_version = envelope.validate_version;
pub const validate_extension = envelope.validate_extension;
pub const validate_envelope = envelope.validate_envelope;
pub const packet_header_bytes = packet_envelope.packet_header_bytes;
pub const max_packet_payload_bytes = packet_envelope.max_packet_payload_bytes;
pub const PacketEnvelopeError = packet_envelope.PacketEnvelopeError;
pub const encode_packet = packet_envelope.encode_packet;
pub const decode_packet = packet_envelope.decode_packet;
pub const TransportCapability = capability_negotiation.TransportCapability;
pub const ChannelCapability = capability_negotiation.ChannelCapability;
pub const SecurityCapability = capability_negotiation.SecurityCapability;
pub const CompressionCapability = capability_negotiation.CompressionCapability;
pub const CapabilityOffer = capability_negotiation.CapabilityOffer;
pub const NegotiatedCapabilities = capability_negotiation.NegotiatedCapabilities;
pub const CapabilityNegotiationError = capability_negotiation.CapabilityNegotiationError;
pub const negotiate_capabilities = capability_negotiation.negotiate_capabilities;
pub const critical_extension_first = extension_handling.critical_extension_first;
pub const ExtensionHandling = extension_handling.ExtensionHandling;
pub const ExtensionHandlingError = extension_handling.ExtensionHandlingError;
pub const handle_extension = extension_handling.handle_extension;
pub const max_reliable_ordered_window = reliable_ordered.max_reliable_ordered_window;
pub const ReliableOrderedError = reliable_ordered.ReliableOrderedError;
pub const ReliableReceiveResult = reliable_ordered.ReliableReceiveResult;
pub const ReliableOrderedMessage = reliable_ordered.ReliableOrderedMessage;
pub const ReliableOrderedReceiver = reliable_ordered.ReliableOrderedReceiver;
pub const SequencedReceiveResult = unreliable_sequenced.SequencedReceiveResult;
pub const UnreliableSequencedReceiver = unreliable_sequenced.UnreliableSequencedReceiver;
pub const is_newer_sequence = unreliable_sequenced.is_newer_sequence;
pub const max_ack_ranges = ack_ranges.max_ack_ranges;
pub const AckRangeError = ack_ranges.AckRangeError;
pub const AckRange = ack_ranges.AckRange;
pub const AckRanges = ack_ranges.AckRanges;
pub const max_retransmission_entries = retransmission.max_retransmission_entries;
pub const RetransmissionError = retransmission.RetransmissionError;
pub const RetransmissionConfig = retransmission.RetransmissionConfig;
pub const RetransmissionEntry = retransmission.RetransmissionEntry;
pub const RetransmissionPollResult = retransmission.RetransmissionPollResult;
pub const RetransmissionScheduler = retransmission.RetransmissionScheduler;
pub const RouteId = congestion_controller.RouteId;
pub const CongestionFeedback = congestion_controller.CongestionFeedback;
pub const CongestionController = congestion_controller.CongestionController;
pub const max_baseline_congestion_routes = baseline_congestion.max_baseline_congestion_routes;
pub const BaselineCongestionError = baseline_congestion.BaselineCongestionError;
pub const BaselineCongestionConfig = baseline_congestion.BaselineCongestionConfig;
pub const BaselineCongestionRouteState = baseline_congestion.BaselineCongestionRouteState;
pub const BaselineCongestionController = baseline_congestion.BaselineCongestionController;
pub const max_paced_routes = packet_pacing.max_paced_routes;
pub const PacingError = packet_pacing.PacingError;
pub const PacingConfig = packet_pacing.PacingConfig;
pub const PacingReservation = packet_pacing.PacingReservation;
pub const PacketPacer = packet_pacing.PacketPacer;
pub const max_bandwidth_routes = bandwidth_caps.max_bandwidth_routes;
pub const BandwidthCapError = bandwidth_caps.BandwidthCapError;
pub const BandwidthDirection = bandwidth_caps.BandwidthDirection;
pub const TrafficClass = bandwidth_caps.TrafficClass;
pub const BandwidthDirectionConfig = bandwidth_caps.BandwidthDirectionConfig;
pub const BandwidthCapConfig = bandwidth_caps.BandwidthCapConfig;
pub const BandwidthLimiter = bandwidth_caps.BandwidthLimiter;
pub const max_backpressure_targets = backpressure.max_backpressure_targets;
pub const BackpressureError = backpressure.BackpressureError;
pub const BackpressureTarget = backpressure.BackpressureTarget;
pub const BackpressureState = backpressure.BackpressureState;
pub const BackpressureConfig = backpressure.BackpressureConfig;
pub const BackpressureSignal = backpressure.BackpressureSignal;
pub const BackpressureCallback = backpressure.BackpressureCallback;
pub const BackpressureController = backpressure.BackpressureController;
pub const package_name = "protocol";

comptime {
    _ = core.package_name;
}

test "protocol package boundary" {
    try @import("std").testing.expectEqualStrings("protocol", package_name);
}

test {
    _ = @import("wire_envelope.zig");
    _ = @import("packet_envelope.zig");
    _ = @import("capability_negotiation.zig");
    _ = @import("extension_handling.zig");
    _ = @import("reliable_ordered.zig");
    _ = @import("unreliable_sequenced.zig");
    _ = @import("ack_ranges.zig");
    _ = @import("retransmission.zig");
    _ = @import("congestion_controller.zig");
    _ = @import("baseline_congestion.zig");
    _ = @import("packet_pacing.zig");
    _ = @import("bandwidth_caps.zig");
    _ = @import("backpressure.zig");
}
