const core = @import("minna-san-core");
const protocol = @import("minna-san-protocol");
const transport = @import("minna-san-transport");
const shard_directory = @import("shard_directory.zig");
const shard_handoff = @import("shard_handoff.zig");
const routed_peer_group = @import("routed_peer_group.zig");
const peer_group_membership = @import("peer_group_membership.zig");
const peer_discovery = @import("peer_discovery.zig");
const nat_candidate = @import("nat_candidate.zig");
const udp_stun_binding = @import("udp_stun_binding.zig");
const tcp_stun_binding = @import("tcp_stun_binding.zig");
const turn_allocation = @import("turn_allocation.zig");
const turn_permissions = @import("turn_permissions.zig");
const turn_channels = @import("turn_channels.zig");
const turn_allocation_lifecycle = @import("turn_allocation_lifecycle.zig");
const turn_relay_transport = @import("turn_relay_transport.zig");

pub const ShardId = shard_directory.ShardId;
pub const ShardHealth = shard_directory.ShardHealth;
pub const ShardRouteKind = shard_directory.ShardRouteKind;
pub const ShardEndpoint = shard_directory.ShardEndpoint;
pub const ShardRoute = shard_directory.ShardRoute;
pub const ShardCapacity = shard_directory.ShardCapacity;
pub const ShardRegistration = shard_directory.ShardRegistration;
pub const ShardDirectoryError = shard_directory.ShardDirectoryError;
pub const ShardDirectoryConfig = shard_directory.ShardDirectoryConfig;
pub const ShardDirectory = shard_directory.ShardDirectory;
pub const HandoffClientId = shard_handoff.HandoffClientId;
pub const ShardHandoffId = shard_handoff.ShardHandoffId;
pub const ShardHandoffRequest = shard_handoff.ShardHandoffRequest;
pub const ShardHandoff = shard_handoff.ShardHandoff;
pub const ShardHandoffError = shard_handoff.ShardHandoffError;
pub const ShardHandoffConfig = shard_handoff.ShardHandoffConfig;
pub const ShardHandoffCoordinator = shard_handoff.ShardHandoffCoordinator;
pub const PeerGroupId = routed_peer_group.PeerGroupId;
pub const PeerGroupPeerId = routed_peer_group.PeerGroupPeerId;
pub const PeerGroupState = routed_peer_group.PeerGroupState;
pub const PeerGroupPath = routed_peer_group.PeerGroupPath;
pub const PeerGroupRoute = routed_peer_group.PeerGroupRoute;
pub const RoutedPeerGroupError = routed_peer_group.RoutedPeerGroupError;
pub const RoutedPeerGroupConfig = routed_peer_group.RoutedPeerGroupConfig;
pub const RoutedPeerGroupInfo = routed_peer_group.RoutedPeerGroupInfo;
pub const RoutedPeerGroups = routed_peer_group.RoutedPeerGroups;
pub const MembershipEventKind = peer_group_membership.MembershipEventKind;
pub const MembershipAuthorization = peer_group_membership.MembershipAuthorization;
pub const MembershipEvent = peer_group_membership.MembershipEvent;
pub const PeerGroupMembershipError = peer_group_membership.PeerGroupMembershipError;
pub const PeerGroupMembershipConfig = peer_group_membership.PeerGroupMembershipConfig;
pub const PeerGroupMembership = peer_group_membership.PeerGroupMembership;
pub const PeerDiscoveryError = peer_discovery.PeerDiscoveryError;
pub const DiscoveryCandidate = peer_discovery.DiscoveryCandidate;
pub const DiscoveryRequest = peer_discovery.DiscoveryRequest;
pub const RendezvousRequest = peer_discovery.RendezvousRequest;
pub const SignalingMessage = peer_discovery.SignalingMessage;
pub const PeerDiscoveryHooks = peer_discovery.PeerDiscoveryHooks;
pub const NatCandidateKind = nat_candidate.NatCandidateKind;
pub const NatCandidateTransport = nat_candidate.NatCandidateTransport;
pub const NatCandidateAddress = nat_candidate.NatCandidateAddress;
pub const NatCandidateCredentials = nat_candidate.NatCandidateCredentials;
pub const NatCandidate = nat_candidate.NatCandidate;
pub const NatCandidateError = nat_candidate.NatCandidateError;
pub const validate_nat_candidate = nat_candidate.validate_nat_candidate;
pub const candidate_expired = nat_candidate.candidate_expired;
pub const UdpStunBindingError = udp_stun_binding.UdpStunBindingError;
pub const UdpStunBindingConfig = udp_stun_binding.UdpStunBindingConfig;
pub const UdpStunBindingSend = udp_stun_binding.UdpStunBindingSend;
pub const UdpStunBindingResult = udp_stun_binding.UdpStunBindingResult;
pub const UdpStunBindingClient = udp_stun_binding.UdpStunBindingClient;
pub const TcpStunBindingError = tcp_stun_binding.TcpStunBindingError;
pub const TcpStunBindingConfig = tcp_stun_binding.TcpStunBindingConfig;
pub const TcpStunBindingResult = tcp_stun_binding.TcpStunBindingResult;
pub const TcpStunBindingClient = tcp_stun_binding.TcpStunBindingClient;
pub const TurnAllocationError = turn_allocation.TurnAllocationError;
pub const TurnAllocationConfig = turn_allocation.TurnAllocationConfig;
pub const TurnAllocation = turn_allocation.TurnAllocation;
pub const TurnAllocationClient = turn_allocation.TurnAllocationClient;
pub const TurnPermissionError = turn_permissions.TurnPermissionError;
pub const TurnPermissionConfig = turn_permissions.TurnPermissionConfig;
pub const TurnPermission = turn_permissions.TurnPermission;
pub const TurnPermissions = turn_permissions.TurnPermissions;
pub const turn_channel_min = turn_channels.turn_channel_min;
pub const turn_channel_max = turn_channels.turn_channel_max;
pub const turn_channel_header_bytes = turn_channels.turn_channel_header_bytes;
pub const TurnChannelError = turn_channels.TurnChannelError;
pub const TurnChannelConfig = turn_channels.TurnChannelConfig;
pub const TurnChannelBinding = turn_channels.TurnChannelBinding;
pub const TurnChannelData = turn_channels.TurnChannelData;
pub const TurnChannels = turn_channels.TurnChannels;
pub const TurnAllocationLifecycleError = turn_allocation_lifecycle.TurnAllocationLifecycleError;
pub const TurnAllocationFailure = turn_allocation_lifecycle.TurnAllocationFailure;
pub const TurnAllocationEvent = turn_allocation_lifecycle.TurnAllocationEvent;
pub const TurnAllocationLifecycleConfig = turn_allocation_lifecycle.TurnAllocationLifecycleConfig;
pub const TurnAllocationLifecycle = turn_allocation_lifecycle.TurnAllocationLifecycle;
pub const TurnRelayTransportError = turn_relay_transport.TurnRelayTransportError;
pub const TurnRelayDatagram = turn_relay_transport.TurnRelayDatagram;
pub const TurnRelayIo = turn_relay_transport.TurnRelayIo;
pub const TurnRelayTransport = turn_relay_transport.TurnRelayTransport;

pub const package_name = "topology";

comptime {
    _ = core.package_name;
    _ = protocol.package_name;
    _ = transport.package_name;
}

test "topology package boundary" {
    try @import("std").testing.expectEqualStrings("topology", package_name);
}

test {
    _ = @import("shard_directory.zig");
    _ = @import("shard_handoff.zig");
    _ = @import("routed_peer_group.zig");
    _ = @import("peer_group_membership.zig");
    _ = @import("peer_discovery.zig");
    _ = @import("nat_candidate.zig");
    _ = @import("udp_stun_binding.zig");
    _ = @import("tcp_stun_binding.zig");
    _ = @import("turn_allocation.zig");
    _ = @import("turn_permissions.zig");
    _ = @import("turn_channels.zig");
    _ = @import("turn_allocation_lifecycle.zig");
    _ = @import("turn_relay_transport.zig");
}
