const core = @import("minna-san-core");
const protocol = @import("minna-san-protocol");
const transport = @import("minna-san-transport");
const topology = @import("minna-san-topology");
const state = @import("minna-san-state");
const sdk_config = @import("sdk_config.zig");
const resource_handle = @import("resource_handle.zig");
const buffer_api = @import("buffer_api.zig");
const event = @import("event.zig");
const poll_runtime = @import("poll_runtime.zig");
const managed_runtime = @import("managed_runtime.zig");
const authoritative_host = @import("authoritative_host.zig");
const authoritative_client = @import("authoritative_client.zig");
const authoritative_admission = @import("authoritative_admission.zig");
const interest_management = @import("interest_management.zig");
const spatial_grid_interest = @import("spatial_grid_interest.zig");
const version = @import("version.zig");

pub const ConfigError = sdk_config.ConfigError;
pub const SdkConfig = sdk_config.SdkConfig;
pub const Sdk = sdk_config.Sdk;
pub const SdkConfigBuilder = sdk_config.SdkConfigBuilder;
pub const HandleError = resource_handle.HandleError;
pub const ResourceHandle = resource_handle.ResourceHandle;
pub const ResourceRegistry = resource_handle.ResourceRegistry;
pub const SdkBuffer = buffer_api.SdkBuffer;
pub const EventMode = event.EventMode;
pub const EventOwnership = event.EventOwnership;
pub const EventBuffer = event.EventBuffer;
pub const MessageEvent = event.MessageEvent;
pub const OverflowEvent = event.OverflowEvent;
pub const EventKind = event.EventKind;
pub const Event = event.Event;
pub const EventEnvelope = event.EventEnvelope;
pub const EventOrderError = event.EventOrderError;
pub const EventOrder = event.EventOrder;
pub const PollRuntimeError = poll_runtime.PollRuntimeError;
pub const PollRuntime = poll_runtime.PollRuntime;
pub const ManagedRuntimeError = managed_runtime.ManagedRuntimeError;
pub const ManagedRuntime = managed_runtime.ManagedRuntime;
pub const DirectDispatch = managed_runtime.DirectDispatch;
pub const HostPeerId = authoritative_host.HostPeerId;
pub const HostChannelId = authoritative_host.HostChannelId;
pub const SessionOwner = authoritative_host.SessionOwner;
pub const RouteDirection = authoritative_host.RouteDirection;
pub const AuthoritativeHostError = authoritative_host.AuthoritativeHostError;
pub const AuthoritativeHostConfig = authoritative_host.AuthoritativeHostConfig;
pub const HostTick = authoritative_host.HostTick;
pub const RoutedHostMessage = authoritative_host.RoutedHostMessage;
pub const AuthoritativeHost = authoritative_host.AuthoritativeHost;
pub const AuthoritativeClientState = authoritative_client.AuthoritativeClientState;
pub const AuthoritativeClientError = authoritative_client.AuthoritativeClientError;
pub const AuthoritativeClientConfig = authoritative_client.AuthoritativeClientConfig;
pub const ClientHello = authoritative_client.ClientHello;
pub const HostWelcome = authoritative_client.HostWelcome;
pub const ClientInput = authoritative_client.ClientInput;
pub const AuthoritativeEvent = authoritative_client.AuthoritativeEvent;
pub const AuthoritativeClient = authoritative_client.AuthoritativeClient;
pub const AdmissionDecision = authoritative_admission.AdmissionDecision;
pub const AuthoritativeAdmissionError = authoritative_admission.AuthoritativeAdmissionError;
pub const AdmissionRequest = authoritative_admission.AdmissionRequest;
pub const AdmissionAuthorization = authoritative_admission.AdmissionAuthorization;
pub const AuthoritativeAdmissionConfig = authoritative_admission.AuthoritativeAdmissionConfig;
pub const AuthoritativeAdmission = authoritative_admission.AuthoritativeAdmission;
pub const InterestEntityId = interest_management.InterestEntityId;
pub const InterestSubscriptionId = interest_management.InterestSubscriptionId;
pub const InterestError = interest_management.InterestError;
pub const Visibility = interest_management.Visibility;
pub const InterestSubscription = interest_management.InterestSubscription;
pub const InterestQuery = interest_management.InterestQuery;
pub const InterestUpdate = interest_management.InterestUpdate;
pub const VisibilityChange = interest_management.VisibilityChange;
pub const InterestManagement = interest_management.InterestManagement;
pub const GridPosition = spatial_grid_interest.GridPosition;
pub const GridRegion = spatial_grid_interest.GridRegion;
pub const GridEntityUpdate = spatial_grid_interest.GridEntityUpdate;
pub const SpatialGridInterestError = spatial_grid_interest.SpatialGridInterestError;
pub const SpatialGridInterestConfig = spatial_grid_interest.SpatialGridInterestConfig;
pub const SpatialGridInterest = spatial_grid_interest.SpatialGridInterest;
pub const SdkVersion = version.SdkVersion;
pub const runtime_version = version.runtime_version;
pub const abi_version = version.abi_version;
pub const feature_version = version.feature_version;
pub const wire_version = version.wire_version;
pub const package_name = "runtime";

comptime {
    _ = core.package_name;
    _ = protocol.package_name;
    _ = transport.package_name;
    _ = topology.package_name;
    _ = state.package_name;
}

test "runtime package boundary" {
    try @import("std").testing.expectEqualStrings("runtime", package_name);
}

test {
    _ = @import("sdk_config.zig");
    _ = @import("resource_handle.zig");
    _ = @import("buffer_api.zig");
    _ = @import("event.zig");
    _ = @import("poll_runtime.zig");
    _ = @import("managed_runtime.zig");
    _ = @import("authoritative_host.zig");
    _ = @import("authoritative_client.zig");
    _ = @import("authoritative_admission.zig");
    _ = @import("interest_management.zig");
    _ = @import("spatial_grid_interest.zig");
    _ = @import("version.zig");
    _ = @import("topology_fault_scenarios.zig");
}
