license_id = "BUSL-1.1"
licensor = "Gabriel Ong Zhe Mian"
licensed_work = "minna-san version 0.1.0"
release = "0.1.0"
first_public_distribution_date = "2026-07-16"
change_date = "2030-07-16"
change_license = "Apache-2.0"
additional_use_grant = "None"
