const std = @import("std");

pub const core = struct {
    pub const App = @import("app.zig");
    pub const StepClock = @import("app.zig").StepClock;
    pub const Color = @import("color.zig").Color;
    pub const Vec2 = @import("math.zig").Vec2;
    pub const Rect = @import("math.zig").Rect;
};

pub const input = struct {
    pub const Input = @import("input.zig").Input;
    pub const Key = @import("input.zig").Key;
    pub const Pointer = @import("input.zig").Pointer;
    pub const PointerButton = @import("input.zig").PointerButton;
    pub const Gamepad = @import("input.zig").Gamepad;
    pub const GamepadButton = @import("input.zig").GamepadButton;
    pub const GamepadAxis = @import("input.zig").GamepadAxis;
    pub const Action = @import("actions.zig").Action;
    pub const ActionBinding = @import("actions.zig").Binding;
    pub const ActionMap = @import("actions.zig").Map;
    pub const InspectorInputPanel = @import("inspector_panels.zig").InputPanel;
};

pub const graphics = struct {
    pub const Canvas = @import("canvas.zig").Canvas;
    pub const Sprite = @import("canvas.zig").Sprite;
    pub const ClipRect = @import("canvas.zig").ClipRect;
    pub const BlendMode = @import("canvas.zig").BlendMode;
    pub const Camera2D = @import("camera.zig").Camera2D;
    pub const CameraCanvas = @import("camera_canvas.zig").CameraCanvas;
    pub const Inspector = @import("inspector.zig").Inspector;
    pub const InspectorPanel = @import("inspector.zig").Panel;
    pub const InspectorVisibility = @import("inspector.zig").Visibility;
    pub const InspectorAssetPanel = @import("inspector_panels.zig").AssetPanel;
    pub const InspectorResource = @import("inspector_panels.zig").Resource;
    pub const InspectorResourceHandle = @import("inspector_panels.zig").ResourceHandle;
    pub const InspectorCollisionPanel = @import("inspector_panels.zig").CollisionPanel;
    pub const InspectorPhysicsPanel = @import("inspector_panels.zig").PhysicsPanel;
    pub const InspectorPhysicsState = @import("inspector_panels.zig").PhysicsState;
    pub const Presentation = @import("presentation.zig").Presentation;
    pub const PresentationMode = @import("presentation.zig").PresentationMode;
    pub const HeadlessRenderer = @import("render.zig").HeadlessRenderer;
    pub const FontGlyphRange = @import("font_asset.zig").GlyphRange;
    pub const FontTextDiagnostics = @import("font_asset.zig").TextDiagnostics;
    pub const ShaderAssetHandle = @import("assets.zig").ShaderAssetHandle;
};

pub const assets = struct {
    pub const AssetStore = @import("assets.zig").AssetStore;
    pub const AssetFile = @import("assets.zig").AssetFile;
    pub const AudioHandle = @import("assets.zig").AudioHandle;
    pub const Image = @import("image.zig").Image;
    pub const Atlas = @import("atlas.zig").Atlas;
    pub const Font = @import("font_asset.zig").Font;
    pub const Sound = @import("audio.zig").Sound;
    pub const Music = @import("audio.zig").Music;
    pub const AssetStats = @import("assets.zig").AssetStats;
};

pub const world = struct {
    pub const TileMap = @import("tilemap.zig").TileMap;
    pub const TileMapLayer = @import("tilemap.zig").TileMapLayer;
    pub const TileCollider = @import("tile_collision.zig").TileCollider;
    pub const CharacterController = @import("tile_collision.zig").CharacterController;
    pub const collision = @import("collision.zig");
};

pub const preview = @import("preview.zig");
pub const testSupport = @import("test_support.zig");

test "public API excludes effects GPU resource declarations" {
    try std.testing.expect(!@hasDecl(@This(), "GpuResourceKind"));
    try std.testing.expect(!@hasDecl(@This(), "GpuResources"));
    try std.testing.expect(!@hasDecl(@This(), "TextureHandle"));
    try std.testing.expect(!@hasDecl(@This(), "RenderTargetHandle"));
    try std.testing.expect(!@hasDecl(@This(), "ShaderHandle"));
    try std.testing.expect(!@hasDecl(@This(), "PipelineHandle"));
    try std.testing.expect(!@hasDecl(@This(), "ShaderProgram"));
    try std.testing.expect(!@hasDecl(@This(), "ShaderReflection"));
    try std.testing.expect(!@hasDecl(@This(), "ShaderKind"));
    try std.testing.expect(!@hasDecl(@This(), "PixelEffect"));
    try std.testing.expect(!@hasDecl(@This(), "PixelEffectParameters"));
    try std.testing.expect(!@hasDecl(@This(), "PostProcessChain"));
    try std.testing.expect(!@hasDecl(@This(), "LightingPipeline"));
    try std.testing.expect(!@hasDecl(@This(), "LightingConfig"));
    try std.testing.expect(!@hasDecl(@This(), "Light"));
    try std.testing.expect(!@hasDecl(@This(), "LightOccluder"));
    try std.testing.expect(!@hasDecl(@This(), "LightingMetrics"));
    try std.testing.expect(!@hasDecl(@This(), "LightingRenderPath"));
    try std.testing.expect(!@hasDecl(@This(), "lighting"));
    try std.testing.expect(!@hasDecl(@This(), "NetMessage"));
    try std.testing.expect(!@hasDecl(@This(), "NetContract"));
    try std.testing.expect(!@hasDecl(@This(), "NetTransport"));
    try std.testing.expect(!@hasDecl(@This(), "P2pPeer"));
    try std.testing.expect(!@hasDecl(@This(), "PredictionClient"));
    try std.testing.expect(!@hasDecl(@This(), "FaultNetwork"));
    try std.testing.expect(!@hasDecl(@This(), "netCodec"));
    try std.testing.expect(!@hasDecl(@This(), "InspectorNetworkPanel"));
    try std.testing.expect(!@hasDecl(graphics, "InspectorNetworkPanel"));
    try std.testing.expect(!@hasDecl(@This(), "UiFrame"));
    try std.testing.expect(!@hasDecl(@This(), "UiId"));
    try std.testing.expect(!@hasDecl(@This(), "UiLayout"));
    try std.testing.expect(!@hasDecl(@This(), "UiResponse"));
    try std.testing.expect(!@hasDecl(@This(), "UiState"));
    try std.testing.expect(!@hasDecl(@This(), "UiStyle"));
    try std.testing.expect(!@hasDecl(@This(), "UiSurface"));
    try std.testing.expect(!@hasDecl(@This(), "ui"));
    try std.testing.expect(!@hasDecl(graphics, "UiFrame"));
    try std.testing.expect(!@hasDecl(graphics, "UiId"));
    try std.testing.expect(!@hasDecl(graphics, "UiLayout"));
    try std.testing.expect(!@hasDecl(graphics, "UiResponse"));
    try std.testing.expect(!@hasDecl(graphics, "UiState"));
    try std.testing.expect(!@hasDecl(graphics, "UiStyle"));
    try std.testing.expect(!@hasDecl(graphics, "UiSurface"));
}
pub const App = @import("app.zig");
pub const AudioMixer = @import("audio.zig").AudioMixer;
pub const AudioSample = @import("audio.zig").AudioSample;
pub const Animation = @import("atlas.zig").Animation;
pub const ActionBinding = @import("actions.zig").Binding;
pub const Action = @import("actions.zig").Action;
pub const ActionMap = @import("actions.zig").Map;
pub const AnimationFrame = @import("atlas.zig").AnimationFrame;
pub const AnimationHandle = @import("atlas.zig").AnimationHandle;
pub const AnimationPlayer = @import("atlas.zig").AnimationPlayer;
pub const AnimationStateMachine = @import("animation_state.zig").Machine;
pub const AnimationState = @import("animation_state.zig").State;
pub const AnimationTransition = @import("animation_state.zig").Transition;
pub const AnimationStateDiagnostic = @import("animation_state.zig").Diagnostic;
pub const animationState = @import("animation_state.zig");
pub const Atlas = @import("atlas.zig").Atlas;
pub const AtlasFrame = @import("atlas.zig").AtlasFrame;
pub const AtlasFrameHandle = @import("atlas.zig").AtlasFrameHandle;
pub const AtlasHandle = @import("assets.zig").AtlasHandle;
pub const AudioHandle = @import("assets.zig").AudioHandle;
pub const AssetFile = @import("assets.zig").AssetFile;
pub const AssetStore = @import("assets.zig").AssetStore;
pub const Font = @import("font_asset.zig").Font;
pub const FontGlyph = @import("font_asset.zig").Glyph;
pub const FontHandle = @import("assets.zig").FontHandle;
pub const FontLoadOptions = @import("font_asset.zig").LoadOptions;
pub const FontGlyphRange = @import("font_asset.zig").GlyphRange;
pub const FontTextDiagnostics = @import("font_asset.zig").TextDiagnostics;
pub const BusHandle = @import("audio.zig").BusHandle;
pub const Broadphase = @import("broadphase.zig").Broadphase;
pub const BroadphaseProxy = @import("broadphase.zig").Proxy;
pub const Camera2D = @import("camera.zig").Camera2D;
pub const CameraBounds = @import("camera.zig").CameraBounds;
pub const CameraCanvas = @import("camera_canvas.zig").CameraCanvas;
pub const CameraDirector = @import("camera.zig").CameraDirector;
pub const CameraFollow = @import("camera.zig").CameraFollow;
pub const CameraHandle = @import("camera.zig").CameraHandle;
pub const CameraRig = @import("camera.zig").CameraRig;
pub const CameraShake = @import("camera.zig").CameraShake;
pub const CameraShot = @import("camera.zig").CameraShot;
pub const CameraViewport = @import("camera.zig").CameraViewport;
pub const Canvas = @import("canvas.zig").Canvas;
pub const ClipRect = @import("canvas.zig").ClipRect;
pub const BlendMode = @import("canvas.zig").BlendMode;
pub const Color = @import("color.zig").Color;
pub const DiagnosticCapture = @import("diagnostics.zig").Input;
pub const DiagnosticCaptureOptions = @import("diagnostics.zig").Options;
pub const diagnostics = @import("diagnostics.zig");
pub const Circle = @import("collision.zig").Circle;
pub const Segment = @import("collision.zig").Segment;
pub const AssetCatalog = @import("asset_catalog.zig").Source;
pub const AssetCatalogDiagnostic = @import("asset_catalog.zig").Diagnostic;
pub const AssetCatalogGraph = @import("asset_catalog.zig").Graph;
pub const assetCatalog = @import("asset_catalog.zig");
pub const contentCache = @import("content_cache.zig");
pub const MapSource = @import("map_source.zig").Source;
pub const MapSourceDiagnostic = @import("map_source.zig").Diagnostic;
pub const mapSource = @import("map_source.zig");
pub const Polygon = @import("collision.zig").Polygon;
pub const ParticleEmitter = @import("particles.zig").Emitter;
pub const ParticleConfig = @import("particles.zig").Config;
pub const ParticleMetrics = @import("particles.zig").Metrics;
pub const particles = @import("particles.zig");
pub const FrameProfiler = @import("profiler.zig").Profiler;
pub const ProfileMetrics = @import("profiler.zig").Metrics;
pub const ProfileScope = @import("profiler.zig").Scope;
pub const ProfileScopeMetrics = @import("profiler.zig").ScopeMetrics;
pub const ProfileSample = @import("profiler.zig").Sample;
pub const ProfileTimer = @import("profiler.zig").Timer;
pub const profiler = @import("profiler.zig");
pub const RuntimeMetrics = @import("runtime_metrics.zig").Metrics;
pub const runtimeMetrics = @import("runtime_metrics.zig");
pub const CollisionContact = @import("collision.zig").Contact;
pub const CollisionRayHit = @import("collision.zig").RayHit;
pub const collision = @import("collision.zig");
pub const CharacterConfig = @import("tile_collision.zig").CharacterConfig;
pub const CharacterController = @import("tile_collision.zig").CharacterController;
pub const CharacterState = @import("tile_collision.zig").CharacterState;
pub const TileCollider = @import("tile_collision.zig").TileCollider;
pub const TileCollisionHit = @import("tile_collision.zig").Hit;
pub const TileCollisionShape = @import("tile_collision.zig").Shape;
pub const DrawSpriteOptions = @import("atlas.zig").DrawSpriteOptions;
pub const EcsEntity = @import("ecs.zig").Entity;
pub const EcsWorld = @import("ecs.zig").World;
pub const EcsCommands = @import("ecs.zig").Commands;
pub const ComponentStore = @import("ecs.zig").ComponentStore;
pub const SpriteSampling = @import("atlas.zig").Sampling;
pub const Image = @import("image.zig").Image;
pub const ImageDecodeOptions = @import("image.zig").DecodeOptions;
pub const ImageHandle = @import("assets.zig").ImageHandle;
pub const Input = @import("input.zig").Input;
pub const Inspector = @import("inspector.zig").Inspector;
pub const InspectorLogger = @import("inspector.zig").Logger;
pub const InspectorPanel = @import("inspector.zig").Panel;
pub const InspectorVisibility = @import("inspector.zig").Visibility;
pub const inspector = @import("inspector.zig");
pub const InspectorAssetPanel = @import("inspector_panels.zig").AssetPanel;
pub const InspectorInputPanel = @import("inspector_panels.zig").InputPanel;
pub const InspectorResource = @import("inspector_panels.zig").Resource;
pub const InspectorResourceHandle = @import("inspector_panels.zig").ResourceHandle;
pub const InspectorMetricsPanel = @import("inspector_panels.zig").MetricsPanel;
pub const InspectorCollisionPanel = @import("inspector_panels.zig").CollisionPanel;
pub const InspectorPhysicsPanel = @import("inspector_panels.zig").PhysicsPanel;
pub const InspectorPhysicsState = @import("inspector_panels.zig").PhysicsState;
pub const inspectorPanels = @import("inspector_panels.zig");
pub const Gamepad = @import("input.zig").Gamepad;
pub const GamepadButton = @import("input.zig").GamepadButton;
pub const GamepadAxis = @import("input.zig").GamepadAxis;
pub const Key = @import("input.zig").Key;
pub const Music = @import("audio.zig").Music;
pub const InputReplay = @import("input_replay.zig").Replay;
pub const InputReplayButton = @import("input_replay.zig").Button;
pub const InputReplayRecorder = @import("input_replay.zig").Recorder;
pub const parseInputReplay = @import("input_replay.zig").parse;
pub const MusicOptions = @import("audio.zig").MusicOptions;
pub const PlaybackHandle = @import("audio.zig").PlaybackHandle;
pub const Pointer = @import("input.zig").Pointer;
pub const PointerButton = @import("input.zig").PointerButton;
pub const Presentation = @import("presentation.zig").Presentation;
pub const PresentationMode = @import("presentation.zig").PresentationMode;
pub const PresentationRect = @import("presentation.zig").PresentationRect;
pub const PrimitiveBatch = @import("primitive_batch.zig").PrimitiveBatch;
pub const PrimitiveBatchDraw = @import("primitive_batch.zig").Draw;
pub const PrimitiveBatchPoint = @import("primitive_batch.zig").Point;
pub const PrimitiveBatchVertex = @import("primitive_batch.zig").Vertex;
pub const Rect = @import("math.zig").Rect;
pub const ReloadEvent = @import("assets.zig").ReloadEvent;
pub const ReloadStatus = @import("assets.zig").ReloadStatus;
pub const RenderCommand = @import("render.zig").Command;
pub const RenderCommandBuffer = @import("render.zig").CommandBuffer;
pub const HeadlessRenderer = @import("render.zig").HeadlessRenderer;
pub const ShaderAssetHandle = @import("assets.zig").ShaderAssetHandle;
pub const Sound = @import("audio.zig").Sound;
pub const SoundOptions = @import("audio.zig").SoundOptions;
pub const Sprite = @import("canvas.zig").Sprite;
pub const SpriteBatch = @import("sprite_batch.zig").SpriteBatch;
pub const SpriteBatchGroup = @import("sprite_batch.zig").Batch;
pub const SpriteBatchDraw = @import("sprite_batch.zig").SpriteDraw;
pub const SpriteSourceRect = @import("sprite_batch.zig").SourceRect;
pub const SpriteBatchPoint = @import("sprite_batch.zig").Point;
pub const SpriteBatchUv = @import("sprite_batch.zig").Uv;
pub const SpriteBatchVertex = @import("sprite_batch.zig").Vertex;
pub const StepClock = @import("app.zig").StepClock;
pub const TextHandle = @import("assets.zig").TextHandle;
pub const TextAlignment = @import("text_layout.zig").Alignment;
pub const TextLayoutOptions = @import("text_layout.zig").Options;
pub const TextLayout = @import("text_layout.zig").Layout;
pub const layoutText = @import("text_layout.zig").layout;
pub const TileMapHandle = @import("assets.zig").TileMapHandle;
pub const TileMapAssetOptions = @import("assets.zig").TileMapAssetOptions;
pub const Tile = @import("tilemap.zig").Tile;
pub const TileFlags = @import("tilemap.zig").TileFlags;
pub const TileMap = @import("tilemap.zig").TileMap;
pub const TileMapLayer = @import("tilemap.zig").TileMapLayer;
pub const TileMapLayerKind = @import("tilemap.zig").LayerKind;
pub const TileMapObject = @import("tilemap.zig").MapObject;
pub const TileMapObjectShape = @import("tilemap.zig").ObjectShape;
pub const TileMapProperty = @import("tilemap.zig").Property;
pub const TileMapPropertyValue = @import("tilemap.zig").PropertyValue;
pub const TileSet = @import("tilemap.zig").TileSet;
pub const Vec2 = @import("math.zig").Vec2;
