name: Toolchain

on:
  pull_request:
  push:

jobs:
  zig-0-15-2:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2
      - run: script/check_zig_version.sh
      - run: script/check_third_party_notices.py
      - run: script/test_core_without_sdl.sh
      - run: zig build test
      - run: zig build check-examples
      - run: zig build test-sdl
      - run: zig build test-box2d
